# Generated by Django 4.0.3 on 2022-05-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='mailId',
            new_name='email',
        ),
    ]
