# Generated by Django 4.0.3 on 2022-05-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_subscribe_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscribe',
        ),
    ]
