# Generated by Django 4.0.3 on 2022-05-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribe',
            new_name='Subscribers',
        ),
    ]
