# Generated by Django 4.0.3 on 2022-05-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_subscribe_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='subscribe',
        ),
    ]
