# Generated by Django 4.0.3 on 2022-05-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_appdawnload_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppDawnload',
        ),
    ]
