# Generated by Django 4.0.3 on 2022-05-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_delete_appdawnload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactUs',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
